[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
authors = ["shixinhuang99 <shixinhuang99@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/shixinhuang99/project-name"
homepage = "https://github.com/shixinhuang99/project-name"
