name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20
          components: clippy, rustfmt

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Fmt
        run: cargo fmt --all -- --check

  tests:
    needs: clippy-fmt
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Test code on ${{ matrix.os }}
        run: cargo +stable test --all-targets
