name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  general-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-04-20
          components: clippy, rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - name: Fmt
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Check
        run: cargo check --all-targets

  tests:
    needs: general-check
    runs-on: ${{ matrix.os }}
    name: tests (${{ matrix.target }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            test: true

    steps:
      - uses: actions/checkout@v3

      - name: Rust cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}

      - name: Test code
        if: matrix.test
        run: |
          rustup target add ${{ matrix.target }}
          cargo test --target ${{ matrix.target }}

      - name: Test cargo build
        if: matrix.test == '' && matrix.cross == ''
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --target ${{ matrix.target }}

      - name: Test cross build
        if: matrix.cross
        run: |
          cargo install cross
          cross build --target ${{ matrix.target }}
