include = ["**/*.toml"]
exclude = ["**/Cargo.lock"]

[formatting]
indent_string = "	"

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "*-dependencies"]

[rule.formatting]
reorder_keys = true
